version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest  # Ensures Docker is pre-installed
  pre_build:
    commands:
      - echo "Updating instance and installing dependencies..."
      - sudo yum update -y
      - sudo yum install -y docker git
      - sudo service docker start || sudo dockerd &
      - git clone https://github.com/davidodediran/AWS-Codepipeline.git
      - cd AWS-Codepipeline
      - echo "Dependencies installed successfully!"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t cat-family .
      - echo "Docker image built successfully!"

  post_build:
    commands:
      - echo "Running the new container with index.html..."
      - docker run -d -p 80:80 --name cat-family cat-family
      - echo "Deployment complete!"

artifacts:
  files:
    - simpleDeploy
